### ISSUE TITLE
Branch - Algona

### ISSUE THREAD

**Issue by bayc** [NREL/HOPP#144]
- [ ] Have owners review branch to identify functionality to include in HOPP
- [ ] Back-merge dev/refactor into respective branches
- [ ] Remove extraneous code
- [ ] Verify that typing is implemented for added code
- [ ] Review and update tests
- [ ] Merge branch and delete old branch

**Comment by camirmas** [comment]
## 8/9 Meeting

- [ ] Refactor diesel generators
  - Define input yaml files for each generator, then remove generator-specific code where possible
- [ ] Implement `attrs` functionality
- [ ] Write unit tests
  - Test each function of the generator class
- [ ] Integrate with HOPP (will discuss more soon)
