### ISSUE TITLE
Branch - wb_csp_dispatch_design

### ISSUE THREAD

**Issue by camirmas** [NREL/HOPP#171]
- [ ] Have owners review branch to identify functionality to include in HOPP
- [ ] Back-merge dev/refactor into respective branches
- [ ] Remove extraneous code
- [ ] Merge branch and delete old branch

**Comment by qualand** [comment]
This functionality was merged into master here fe62dca946b5a1c6c46f1ceee7a07dfaebf46eeb

There has been no development since.
