### ISSUE TITLE
Update HOPP examples

### ISSUE THREAD

**Issue by kbrunik** [NREL/HOPP#372]

**Comment by johnjasa** [comment]
- [ ] [[Jared Thomas]] to share the GitHub repo where the jupyter notebook lives for the HOPP example; distributed DoD example is a maybe
- [ ] [[Kaitlin Brunik]] to look at detailed PV for an example
- [ ] [[Gen Starke]] to look at CSP as an example (Kaitlin can't run it due to Mac bug)
